name: 'Wait for Artifact'
description: This action waits until an artifact with the given name is ready in this GHA "run"
inputs:
  name:
    description: The name of the artifact
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        INPUT_ARTIFACT_NAME: ${{ inputs.name }}
      run: |
        pause=1
        while true; do
          artifacts=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/dfinity/internet-identity/actions/runs/$GITHUB_RUN_ID/artifacts")

          echo "found artifacts:"
          echo "$artifacts"

          if echo "$artifacts" | jq --arg artifact "$INPUT_ARTIFACT_NAME" --exit-status '.artifacts | any(.name == $artifact)'
          then
              echo "found artifact '$INPUT_ARTIFACT_NAME'"
              break;
          fi
          echo "artifact '$INPUT_ARTIFACT_NAME' not found, will retry in $pause seconds"
          sleep "$pause"
          pause=$(( 2*pause ))
        done
